#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Be.BankVanBreda.Online.UI.Phone.Android.Resource", IsApplication=true)]

namespace Be.BankVanBreda.Online.UI.Phone.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Be.BankVanBreda.Online.UI.Phone.Android.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Be.BankVanBreda.Online.UI.Phone.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backspace = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backspace_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_blue = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_digipass_info = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_digipass_info_new = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_digipass_ok = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_digipass_ok_new = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_digipass_on = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_digipass_sign = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_digipass_sign_new = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_red = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_segment_left = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_segment_left_selected = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btn_segment_right = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_segment_right_selected = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_white = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btnred = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btns = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int callout_arrow_down = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int callout_arrow_up = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int callout_arrow_up_white = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int callout_body = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int hint = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_launcher = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_notification = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icn_search = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ico_attachement = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ico_menu_aanmelden = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ico_menu_berichten = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ico_menu_betalingsopdracht = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ico_menu_contact = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ico_menu_faq = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ico_menu_instellingen = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ico_menu_logout = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ico_menu_overzicht = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ico_menu_registreer = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ico_menu_te_tekenen = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ico_menu_wijzigen_pincode = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ico_move_up = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int icon_add = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int icon_add_begunstigde = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int icon_archive = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int icon_back = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int icon_back_circle = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int icon_back_circle_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int icon_back_circle_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int icon_back_circle_white = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int icon_check = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int icon_check_disabled = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int icon_checkbox_checked = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int icon_checkbox_checked_white = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int icon_checkbox_unchecked = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int icon_checkbox_unchecked_white = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int icon_close = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int icon_close_dark = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int icon_close_dark2 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int icon_close_dark3 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int icon_close_light = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int icon_delete_date = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int icon_draggable = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int icon_menu = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int icon_menu1 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int icon_menu10 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int icon_menu2 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int icon_menu3 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int icon_menu4 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int icon_menu5 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int icon_menu6 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int icon_menu7 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int icon_menu8 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int icon_menu9 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int icon_menu_android = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int icon_menu_android_1 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int icon_menu_android_2 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int icon_menu_android_3 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int icon_menu_android_4 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int icon_menu_android_5 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int icon_menu_android_6 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int icon_menu_android_7 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int icon_menu_android_8 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int icon_menu_android_9 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int icon_menu_android_more = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int icon_new_message = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int icon_next = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int icon_next_disabled = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int icon_next_green = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int icon_next_light = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int icon_not_signed = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int icon_select_list = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int icon_select_next_period = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int icon_select_prev_period = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int icon_select_tip = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int icon_sign = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int icon_sign_disabled = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int icon_signed = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int icon_to_sign = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int img_active_slider = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int img_app_icon = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int img_contact_bvbr_avatar = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int img_counter = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int img_counter_blue = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int img_logo_card_stop = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int img_outline_logo_bvbr = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int img_shadow_menu = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int img_slider = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int img_step = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int img_step_active = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int img_step_done = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int img_tutorial_add_betaling = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int input_code_big = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int input_code_big_white = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int input_code_small = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int input_code_small_white = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int iTunesArtwork = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int label_new_message = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int line = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int line_click = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int line_error = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int loader_00000 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int loader_00001 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int loader_00002 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int loader_00003 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int loader_00004 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int loader_00005 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int loader_00006 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int loader_00007 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int loader_00008 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int loader_00009 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int loader_00010 = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int loader_00011 = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int loader_00012 = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int loader_00013 = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int loader_00014 = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int loader_00015 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int loader_00016 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int loader_00017 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int loader_00018 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int loader_00019 = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int logo_bvbr_outline = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int logo_bvbr_outline_white = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int menu_fg = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int playstore_icon = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int rounded_border = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int search_box = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int semitransparant = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int splash = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int tab = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int tab_selected = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int tabls = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int tablu = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int tabrs = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int tabru = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int transparant = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int transparant_keyboard = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int transparent = 2130837660;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
